---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/main/docker/data/logstash/config/logstash-full.yml

node.name: logstash
http.host: 0.0.0.0

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ['http://elasticsearch:9200']
xpack.monitoring.elasticsearch.username: kibana_system
xpack.monitoring.elasticsearch.password: '${LOGSTASH_INTERNAL_PASSWORD}'
